### ISSUE TITLE
Suggestion Manage Modules tab: show different hint/button when no modules are installed

### ISSUE THREAD

**Issue by Taschenbuch** [blish-hud/Blish-HUD#948] opened 2024-03-11 16:20 UTC
current behavior:
- see screenshot below
- suggest manually installing modules
- button opens modules in windows explorer

suggested behavior:
- Show a different hint like "You dont currently have any modules. Install some modules via "Module Repo" Tab"
- remove button OR let it open the "Module Repo" tab instead

![image](https://github.com/blish-hud/Blish-HUD/assets/43114787/9fdc3dd0-1a87-4098-9ed8-305f4c3373eb)

**Comment by dlamkins** [comment] 2024-03-11 17:11
Good ideas.  Duplicate of #519.  🙂

**Closed as completed by dlamkins** 2024-03-11 17:11 UTC
