### ISSUE TITLE
Control.BasicTooltipText will not disappear

### ISSUE THREAD

**Issue by agaertner** [blish-hud/Blish-HUD#23] opened 2019-05-23 21:19 UTC
Control.BasicTooltipText will not disappear when BlishHUD window is being closed while the tooltip is open.

Example:
A button shows BasicTooltipText on mouse hover.
On click this button closes the main BlishHUD window.
The BasicToolTipText will not disappear.

**Comment by dlamkins** [comment] 2019-05-28 11:18
https://github.com/dlamkins/BlishHUD/commit/84a9d32f222727c6d2e74b5ccb22360d21ae47ea takes care of a few instances where this can happen, but not the one you're experiencing in the Musician module.

That instance of the issue is a little bit tricker, so I'll have to think of a good solution.  It's hard to fix because the control it's associated with is hidden by the window hiding and not the control itself.  It can't currently detect a parent container (all the way up the chain) when it hides - at least not currently.

I might have Shown & Hidden events cascade down to their children whenever they occur.  I believe that would resolve the issue.

**Comment by dlamkins** [comment] 2019-07-16 17:24
FYI - the changes made in my current work on the Multi-Line Textbox has the `Hidden` event fire for controls when a parent control is hidden.  Once that change is merged, it would take care of this issue, as well.

**Comment by entrhopi** [comment] 2021-11-19 16:57
Is this still considered a thing?
Aka in current dev it will stay open, but as soon as I move the mouse cursor by a pixel it will disappear.

**Comment by dlamkins** [comment] 2021-11-19 17:08
Yeah, technically still an issue.  It's very rare that it ever comes up, though, so it hasn't gotten a lot of attention.  Also, like you said, it does go away the moment the mouse moves, so it's a small issue.  🙂

**Comment by entrhopi** [comment] 2021-11-23 14:52
So, after poking around quite a bit ...
`ActiveControl` is only updated on mouse movement and should be expanded to include mouse clicks and keyboard input.
This would not only fix the issue but also enable us to support changing input fields using `TAB` and `SHIFT-TAB` in the future among other things.

My suggestion is to move `ActiveControl` somewhere more general and reference it in `MouseHandler` and `KeyboardHandler`.

**Comment by entrhopi** [comment] 2021-11-24 11:58
Tooltips from `CornerIcon` seem to be rendered only every other pixel on mouse movement.

**Comment by entrhopi** [comment] 2021-11-24 19:31
> Tooltips from `CornerIcon` seem to be rendered only every other pixel on mouse movement.

Fixed this in #548

**Closed** 2022-02-08 04:54 UTC
Labels: bug, UI
