### ISSUE TITLE
Tybalt's Bug Report [712055508810596462]

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#225] opened 2020-05-18 21:44 UTC
**Tybalt at 5/18/2020 9:34:22 PM +00:00**
> I wanted todo boundary checks in .Update manually, but that's a mess and I remember MouseLeft MouseEntered is way too convinient (if I don't need extra size.) but they do not take a dropdowns selections boundaries into consideration. https://gfycat.com/BronzeConcreteConey

https://gfycat.com/BronzeConcreteConey

REF: https://discordapp.com/channels/531175899588984842/534490472224391169/712055508810596462

**Comment by dlamkins** [comment] 2020-05-20 00:44
Closing as a duplicate of #224 (2 Gorrik instances were running which caused it to double submit).

**Closed as completed by dlamkins** 2020-05-20 00:44 UTC
Labels: bug
