### ISSUE TITLE
Inconsistent scroll speeds

### ISSUE THREAD

**Issue by BlishHUD** [blish-hud/Blish-HUD#151] opened 2019-12-08 20:25 UTC
**QuitarHero at 12/8/2019 8:12:39 PM +00:00**
> > **Bug Report:**
> **Module/Build:** Events and Metas Observer v0.44, Blish v0.4.6+dev276
> **Issue:** The scroll speed of all event categories other than "All Events" scroll based on how long it takes you to scroll through the "All Events" event category, instead of having the same scroll speed that the "All Events" category has.

REF: https://discordapp.com/channels/531175899588984842/534492173362528287/653328108761645067

**Comment by dlamkins** [comment] 2019-12-09 03:04
Closed as a duplicate of #151.

**Closed as completed** 2020-08-28 13:44 UTC
Labels: bug
